# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_PM: ROLE_USER
        ROLE_ADMIN: ROLE_PM
    access_control: 
    - 
        path: ^/login
        roles: IS_AUTHENTICATED_ANONYMOUSLY
        requires_channel: https
    -
        path: ^/logout
        roles: IS_AUTHENTICATED_ANONYMOUSLY
        requires_channel: https
    -    
        path: ^/register
        roles: IS_AUTHENTICATED_ANONYMOUSLY
        requires_channel: https
    -    
        path: ^/endRegister/
        roles: IS_AUTHENTICATED_ANONYMOUSLY
        requires_channel: https
    -    
        path: ^/reset
        roles: IS_AUTHENTICATED_ANONYMOUSLY
        requires_channel: https
        
    -   
        path: ^/
        roles: ROLE_USER
        requires_channel: https
      
    encoders: 
        LicenseBundle\Entity\Uzytkownik: 
            algorithm: bcrypt
      
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                provider: our_db_provider

            logout:
                invalidate_session: true
                
            http_basic: ~
            pattern: ^/
            provider: our_db_provider
            
            #pattern: ^/(register)/
            #security: false
            
        secured_area:
            http_basic: ~

            logout:
                invalidate_session: true	  
                path: /logout
                target: /logout
            pattern: ^/
    providers: 
        our_db_provider: 
            entity: 
                class: "LicenseBundle:Uzytkownik"
                property: login
                
        #my_ldap:
            #ldap:
                #service: ldap
                #base_dn: dc=example,dc=com
                #search_dn: "cn=read-only-admin,dc=example,dc=com"
                #search_password: password
                #default_roles: ROLE_USER
                #uid_key: uid
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
