# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    
    
    ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments:
            - ece002v   # host
            - 389         # port
            - 3           # version
            - false       # SSL
            - true        # TLS
